apiVersion: v1
kind: Secret
metadata:
    name: changedetection-secrets
    namespace: default
stringData:
    LLM_API_KEY: ENC[AES256_GCM,data:3snzgEnLHDBINDRlDkaND6sQFl6n1n7uPrlhcJTKYX2nNEgkaUbpsFQ5h19KRXSkRXu4mvek68imWq6ioi6PX4jd/NyvElMZow==,iv:+zbSukRkPyXn6CK8xp2W4U9rn26gqEP3ny1ZvoA+8bY=,tag:lySZ2t7betMSvZSLHuOzTg==,type:str]
    NOTIFICATION_URLS: ENC[AES256_GCM,data:B0z07b1mr1FElPJkio56DYlGNWzdsyYAHUnYh0al4C1+/KIH+P0FZsV9OUjI3G4Qv9Xo1NmRvdwrbQsVpnmMWoR3D8iEuIq9kQoN6bm6577JCRc3v8sj1HwX8xzuCVHWAg==,iv:YzCt2l2qhHPDOFNlaKwyTglZWo7hGvIdZ4/myl3XjA4=,tag:ydrU7D3QnYFfC2IDVwaXwg==,type:str]
sops:
    lastmodified: "2026-05-03T15:40:38Z"
    mac: ENC[AES256_GCM,data:jREl0swsfnqvUptdt1iC7aULUZ4ASICQN4HWVx+u9gsAWpvHANm1F7yQtuB/cBPMz0OjA2DbAHjTlIp5B7/Acc/JgbNTcgnGuB3GImfKTKS6n/cjyHDJ/uDjfLmUmd9F5Rmo4b/kxqlO/JzDfbDzAYV+ZMYFDyPScjqYRpdO0Jg=,iv:Tetxb1vElg13CYJlqU9AF8kByDG9JHJUzJR6MhgCPa0=,tag:u4SclEoNCf45BN9rkLqgbA==,type:str]
    pgp:
        - created_at: "2026-05-03T15:40:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA71EESEn7N2iAQv/ZMae+yAmwkD7TyHcRaiB9L11Z49Z3CE9beGsGlJx1cV0
            SmxQ85sZKu/7vvK2F/fKDaGP4DedthFsanid2rN/k/51TXUm07VWmuNrqUq3sTqG
            b3gPJCXgAFDc/xyAYbU1ISRlX5HfKmTzcw426hnNi/rFZv6yh1UZbgqgEAqGcoL1
            3nZSCkzmKKJ7bKS7roS05mmB37FR+uW1WUg2MbFnRBhBpEZN2uOY3h0U5nDOuQ97
            dnv2p07cdpOjDNw68cu0Rc5S2fF4mEoVWh1X2tUxy87e15QPw4Fr7PhyiFndeXWt
            RrfwW/13dnYP+w2miKJEQAxgWlmxLwkhM4EiyJWnpiH40IOLHk913y/eeHDGtqvQ
            RnQHlkNGPGi9zrB47Pmml2kZRqDDXQmyJ95yvJ2rlsdD69N1l4sffGzYbt8A+oxe
            FcrdMLHzCiEh5ujyxFuSwORA1ULi+8mKUBqDdNUdTNK5DIK7rKKCUnUrVzysDnNh
            YW5LkBN5WKghadr2NBDY0lwBQGe1fc4w8i9cNijzlng5qVsdTt9vH7OPZNhSDPpR
            7QFGuO/Q0ZuQnSbqhvc7zLPpuFd16prFzAfU2VVOqCkMSug1qu6GpJwefzH5HVxT
            rYOGNhfNPm9n/n9N5Q==
            =gdKc
            -----END PGP MESSAGE-----
          fp: 2D47B9C25AAD87860CC1778F7022B8F414F4AEED
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
