apiVersion: v1
kind: Secret
metadata:
    name: changedetection-secrets
    namespace: default
stringData:
    LLM_API_KEY: ENC[AES256_GCM,data:OD3uuBWGt3w3dJ/k8NZiZX3+XwJu26WKZMkl1QMr6ieXjzg+rfiJLLV0nZCaWtu82wYasbkf/fnWW0z3ji9sXNTuNaErEGFToA==,iv:Md3+Zv7QM5Fs53Jyp2ylvEyIDJ7+FuIoyRwf/c5ePQo=,tag:CVdJ/AvxhrTmpNeYtdx6oQ==,type:str]
sops:
    lastmodified: "2026-05-03T14:53:40Z"
    mac: ENC[AES256_GCM,data:Wuat5veAVpMXYtY/v8GNmHBMEdwEZw3nfOqT70uSiPsYBnce3QJBJm2ijcTHTmwc7MFgUsAcbpFd408ITSZqY3yd2eMZd1gWZir+B2py9o5KluJDj7kBpzM0ysZucGqDytL1hKJ/pCSVqOg0QVVHiSl0P0v52h9YO5twMwUQiWk=,iv:jTzcce+u3ZAdZBPwncNYiMjXmlVEXqPyuBNK7pD2LiU=,tag:uBdOvhI9wtlH9qNL+gUpWQ==,type:str]
    pgp:
        - created_at: "2026-05-03T14:53:40Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA71EESEn7N2iAQv/Q4/Rj22cnqXsh/PWvNR4ebwpk1K4VHYYnCTY1XaJc7ra
            0gaHVQDvFy9boFJr5qVFFsD/OpLAOL43/uhlFdw3JUmKb2CjwnaM8L5KayXbNgmi
            GZUwlhrTUWDCHpO1w2GWZHNkrqhoyDCXKuMARb3TDGniqyoFJFrDiWqdHTVVB2RS
            zpGaRvf/6Gl7H1kSJDfgRPKOqgP4WSEhp1C1wK+xOxLOxnbDd8gW9rL8tIcMMWXm
            qTvISPFqSxK8rVR0CopYWiDslzzMUFJw0dRLjnooSdSahPRJqNGeO9cGh0i5peB/
            W/xWLt4jlTDs+CsKNFqmEkIiSefwRUaZccCuw+JMVm/tWpU6r3ZvlZ6UUz2ajkx4
            ZfU8Jq+lrigzHsRcdpPPMiCnnuQQgzo9qmOdqWFiBSmzp3jq2lj9DM7fGd8y6ah6
            yDtuzf4FR1AV8A53CPB9zS+ez49GvJ4BqzNHBXMphHKAJYv4bzCN7lajwUJtpluV
            rGcHf8RdDnrlMnNBOslo0l4BTfNwUKGoD06fKqpSWdZTkck6H7Lu8DJDMbBeQDWm
            rXNE6cH0GMGMns2ucce+xm/RS19TQk6VT0yWHLYDnlhudhKeAl5XKGufdTOEseaG
            ko9LCZGhIJVqI9SfGH80
            =8KeY
            -----END PGP MESSAGE-----
          fp: 2D47B9C25AAD87860CC1778F7022B8F414F4AEED
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
