apiVersion: v1
kind: Secret
metadata:
    name: securo-secrets
    namespace: securo
type: Opaque
stringData:
    #ENC[AES256_GCM,data:PFljGDKYPcH65HHCLZmz4bjUhehswkMzbvElAM34Aud011AwLmTH+KUiSpxOzi1CCFoLqQT2KGDNRGJlpaWfy0U4VA==,iv:CgXf2PN4Tis2rX7cX+EFRaPo/qaJMkbY4DVrvJkrHYE=,tag:D4zagayeE+HRIpLocShTDg==,type:comment]
    SECRET_KEY: ENC[AES256_GCM,data:vO5wXYQFnSnGHI+3WPEsKxQHQow3UC6JATZd9hEevr21GH/HVrFaJ5NpfkTQLCTwMHPn16h22LtNCKIicJdY8WQK3jYVXRvYJdp9SC5+WgYSaHLvbqVR+2ba6ea2X4uz3bJ5a8FKavvrsjM+4VWu3vr4/j3b6e8Jbb/usVIhqo4=,iv:lbflzlJxFykSoowAKvHE9qhrCsnjLgbn7hCBQGKF9eM=,tag:88ch1xbmPg/MyqayCaBa5g==,type:str]
    #ENC[AES256_GCM,data:O9pmj0gFXc9huaqCunbzp35YbCo7l4wfSLabPPaMty3XcH+2RbN/BgZgggMVkFh/xrLfF6zkN6xXS5oHZoTBG0MyEqdK5CaqtmzaGw==,iv:tZXlfXcGxkYQkvs1E3o8VyADyi7XjC7VoMiqPX+LGkg=,tag:gjYSa0qdBMXy6SmuKnvmWg==,type:comment]
    #ENC[AES256_GCM,data:mPSCQZ/zWbri1rGogOhr1QhQhUihKPJAnV2Evnp7zY8dm7LRRi5QpmkHsk5d0rwNdKJNfo7dwgZHAVa2J49GlBYUpfKNbcna9UZPWmgZNsx3,iv:QFXFlMPEG0FMerZKULeyKWlhL1DbnjtkPfcZdM502ko=,tag:LhB1IzaH1kZNK6bsDd3z6A==,type:comment]
    DATABASE_URL: ENC[AES256_GCM,data:r759HxmnjTi+RGGtWR63p40hHfzXtwuGMEOlf+KgmopiszFLSIAHcR6Rk5NZ40iRdUCf+TTsBO31Jlh8aDJlz9wC7/lokOYMev0qM67v8ZnQoF3lVwjQqgW1Nk6wdPRiiA2xtwfV9wQ5ra74e/YWa2Y0fjPFZQ==,iv:clvyf5efdyCwqzFjMNw4SQkxo5arGKmGr8r6VK7W7VM=,tag:dUp9EPvdI1Bt6r8RaM3B9g==,type:str]
    #ENC[AES256_GCM,data:0lAcwK71wj8FdJBVaghn9ZtjCld/z4eWDGuW5j52aVB3NcTqKWLrtC7JzxzcVA6CmX4YV9hCXjD468HLzsxp,iv:eh3yVXfTDHtROz95njxZNlCBQmafnO/cOtqiiu5c7iQ=,tag:ED1nVr//EMmzYOQf3DSWlw==,type:comment]
    #ENC[AES256_GCM,data:WOTJ0N1g+rTIb8zrmQ4vKCb0wYmmWAf8Pku2UWLFM343fKd9IbsV3ldWfo3fHin9bOBUUkrSokQ5A0lQRVBzNZlwYg==,iv:OmFb/7zZCXXHupxt8Aw6NubRqKn710DlxUF7bqahPgM=,tag:J+uugBrRmTwFGNrWteAYGw==,type:comment]
    REDIS_URL: ENC[AES256_GCM,data:HPWgPox7xSdSFsfJeYORzSB5rIwcSPNjXt9FKjC66JatQVC7tuIda552NBDASovbup5f6MQpEi2IxAGV51HCkWg=,iv:p9RIWapz4ID2zqV9KGZLcZRYXnJAsOfpeqr2P5BvKHk=,tag:Nj5fe0qBmaHe+stljfEtVQ==,type:str]
    #ENC[AES256_GCM,data:EwTt4MGp/hJhhzAqejOhO6TJPbM/r6FtSuzJ3hhdrO/HPCyrX1aCZv8AxE79D/0jv+TXf80vITEB1JDfhth4,iv:IepZmGL9w1LUAOfKvHouDhPOn+3NvPgCBjmMH+B5Ofc=,tag:sZmSXbYuLKda9DFfrfITHg==,type:comment]
    #ENC[AES256_GCM,data:dCWgUKpWQ106ZLRYL0rg1X+djpXXp4SDAeTjVLNDJ1DJlBuBzNP75ygUCV7itRRnTt0ocyU3RmWwa0q8Cvp/2jgjTQ==,iv:DRcQMOeNXiwu6saqxQMQAkS5oSMETJFFq3MA2PAfQrs=,tag:gtwZG/Ln4poJO5lnvVNYRQ==,type:comment]
    CELERY_BROKER_URL: ENC[AES256_GCM,data:Fn2PB+Y80VbE6hSq5BCjJSYcNaVlesEbRxB1s3EVdlkmKPuCXOpkE3aJg4YM4HdvclI13Ed7bEAbzCw2vCmgt4o=,iv:KO452BTqZg7ZXzQ3g1p8qtzsWm41fVJXQVQvCYYwM2w=,tag:fCSjVUUWOAX2cEAvGWqJGA==,type:str]
    #ENC[AES256_GCM,data:gwx5MGWrR6w95e4KlRRv/aHgOsYwdfy2+znZmkOzon6rmAsRuYqpUyTmX6RLXDDDN1kVUGHI0XWweazmoexQ,iv:+BKLDJw84ksc/+7gKr6XiF0OkH3hqCv+jkW6w0I9aoo=,tag:hc749+qXLvyScP1qZqxK4w==,type:comment]
    #ENC[AES256_GCM,data:5/+jHx3IWLrPKEo6TIpJHI8IHubFj16nx5HcutPE/ItDBJPRmIe7JOAE2j7GBhY/7JkauwgIm/eMhgtNGB2yU5Nc/g==,iv:AR30IJL4ThCz2tYimAY+QO5j4+Ynl5u1twY6K34VMto=,tag:WgleDGH89D4tn1wAVH3zuw==,type:comment]
    CELERY_RESULT_BACKEND: ENC[AES256_GCM,data:84rBxL42r8HmH7WwBTiVlTLEpPKJFagR792NpmFX4ICvu2JQjwG+xbxpRDGjDPR/enS0EVIbOOELVCycbik928s=,iv:ZF3TnU10IETjjhvECNIrtSRJWz6G1QmVNUtmWyC2mvA=,tag:kE3R7GIsbGuMOKUHdUAkoQ==,type:str]
    #ENC[AES256_GCM,data:quz6ew7rB0fHXdQGsl8QCwy0ls4gHX9lU73jEZ3g5UGtf3l2JKeirJvJWhWI4T2njKaINhEoeJuMAE8=,iv:B4CMDTRnjqFkN8IJfw9dSq3SDwx5gq8NuEfb/zgbGkY=,tag:ovhmQf6BjpfJV00yMgNKGQ==,type:comment]
    AGENTS_MCP_JWT_SECRET: ENC[AES256_GCM,data:DKePZp2sw5ycAiK+oJ4B8plhFD1DftR68pGfNH30yYLFqRf2AjYeavft47acyzsh/kf7kxOwpIKv+CmdxqAYnPWP5I88AHA5XojOfM9x2mmh5ZkiiiCbBTYS6UW5BuOJOY+w90YVcbBO5j94xHZKVCHj1F2etwuVQApOIYrcP+c=,iv:y/8YgUMqalZiaXWIFVh8l+Zwgpyg6f7V1Z4uqEzWWrM=,tag:r3qKZQlBhPZWvr/IKK3y6w==,type:str]
    #ENC[AES256_GCM,data:HynJEhW/F7Aw7Wf0rvzNVp1kGL94ibrmstRmfEbu+RBAnA3SPLjOAmwX1JrmhsA/OTzHyC3bIKEM732JC0Xd8aQmsFmOzjv2bMIp,iv:q+7keptOZr95PirdWbLShHC9YeyDwY4iBmA3+aQHSJQ=,tag:Aux/s9ZJmq3LLk1AocJ/5Q==,type:comment]
    #ENC[AES256_GCM,data:GS4hoSsBbXGbGqQ207MAszYAZw0B5K3MV2tHRx5EYaQYy+yBY6GMCVmsKGwpF9sdmKZMH8l/qHNOTk3k/A==,iv:3QkjUTLRycQFlYkDVDMSmAjQ1LmFkZ5UkCrYjqTMLS8=,tag:iRIPffJmDWkVVH1MQUax/Q==,type:comment]
    AGENTS_EMBEDDING_OPENAI_API_KEY: ENC[AES256_GCM,data:B8eyo+IRF2+P7vyxJg9fQNCfzDHXG+JU7AzT1iYzMpSDD5sN4lrI6g+osz+YPIO3fqnw+75khW7xKZ+ii07oSfNuCWi00tsEzw==,iv:sxIAZVb1OtMAD8nwibusa9DkxGLBh99XdGyLnO2rKzw=,tag:EgAAwwnp49lOsF19Bt8ZnA==,type:str]
    #ENC[AES256_GCM,data:oEIMmsMJn21ZKerD24Hqr4K+2avg35RqNr7s5j4eoGbfkTOKMHpGxbYmvhhWqLWOx5A=,iv:0sYCBieqzFmtTi19zFRVQzsJzGlJwjI0KjRmz1lL5OY=,tag:5kl9OO3DFzv2mauD3yJ03w==,type:comment]
    OPENEXCHANGERATES_APP_ID: ENC[AES256_GCM,data:7zHOL/twL6n33O/yBvD2Xx7j/12Mhw2bkO8pA2dUw7c=,iv:7bV1PcPYkhfVUeIdV+ogLFOv0RKgAcEN6IaJ+5QhtXI=,tag:4l8BULFg4ga7W9suOtrl0g==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-20T20:07:25Z"
    mac: ENC[AES256_GCM,data:8/3ShEJK/Sr3QaTAC65VbRTWr+foTrTwRXjTa7oFEayxUEVl1QLUb/Ixoqbw22GspWQt+olt5aD8P3WBVsY1R3g/zxIHPnLFN01ZZAhFHKDlgD6tq5RL13it3ThgP+LkyOjZm1ce42ux3MWIyNItwYNSdnf9vQbDd2K+Es+XopU=,iv:UI9jX2H3fvCP4IP7yFe0EFha4Tt0yFLmnE/zoZ6ftBs=,tag:xrrDFtAU+TyXHJn/KTEWUg==,type:str]
    pgp:
        - created_at: "2026-09-20T20:07:25Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA71EESEn7N2iAQv7BwGYQQMR34danSgD+ynZ2oT+8bVWBpMw5dIr+t1xE9v3
            iYlulFJwgubuUE6NhN33T1DMb/RRa7+hDAKbzezkCo+bZlIf7wWaPelMa5qvEb/X
            1nWoFNv6Zu96XTwXZ9vOl36ARSKWD/WpDxOX1LsZNjhbxkWQFhOvjPKunp+a5ozn
            9sKzQqYOtjUvT7EBkViUHmAuB0DniwoZYwUPABIRS2Ez1EsPsvHntvkkL6tYFayK
            nMj5jDLeHR3u4IYk2fD0/ClNKK6OvTrjLuDh7xCYY3wpZTNkxkxk7J8ysxLs08WT
            52RCRFDsArOg1jsw1Y/fOZCc7tGjylT7TFUXjvEnM5wnNrYxikxpJFPZljiKAjqc
            cvve9faYHRef8NV7EKiYAwEab+gpQFN+KhMFSweUbWvrjnQlNQIiwCP6SvMmwAvq
            nVYypNbARowShfeeO1/CpQrsOq4K/4pRO0GJdOr9PeujpHh7kxkU2G9p8tfPklKk
            RtK1tBrgV5WNU1Yhr7d80lwBG2LoD7Otzy34S595fMPI4iH1At/nzS83Ed3icPNP
            UH1O7nzkhQxwgu6/+NuFte3N+lEHBdxxdq8gqqJunk5sBDLa67Fp5YpUR8DjCB/0
            Y8nSrO3a+dfz7GDFhQ==
            =LQ3b
            -----END PGP MESSAGE-----
          fp: 2D47B9C25AAD87860CC1778F7022B8F414F4AEED
    version: 3.13.3
