apiVersion: v1
kind: Secret
metadata:
    name: opencode-openchamber-secrets
    namespace: default
stringData:
    OPENCODE_SERVER_PASSWORD: ENC[AES256_GCM,data:UAHrBNKBAzsjFf3Bq8KMfoz6EVnJ5UyB4l9OeePxlynvH28DQ6bDnnTRcQ==,iv:sLq7BVjbtF8ii0wcndjjcBrceap/qyaMVxKTEUSv4ww=,tag:uCnELnCRW9T6dN7ahpS3ig==,type:str]
    OPENCHAMBER_UI_PASSWORD: ENC[AES256_GCM,data:nyx6XKJGyOIlqYvhje8+1sHgVqb6wPaVy1kzjVqQQLcTyX7MUPhU7iK90w==,iv:PLJEk1q24aCffqDCz8o7rhrf3aRolgy/fCRMEz1xxVE=,tag:FkcaiacX5O/nShN4HtF0+g==,type:str]
    OPENCODE_JWT_SECRET: ENC[AES256_GCM,data:me83sCE0WXTOlNtmSp7HnH10RZFM6usG2yECI70Q1kMydaye0y+lXV5DV/JrjsJkYbHqEK/acx940VxFCmeQRTdEYNhzB2lQFBfFXtWFT11eP3NLzfY=,iv:Qil3mixypQrjhk6QGkv++nVll2NwK7f8cwYg3ZyuaVM=,tag:Mbw81iw8ctDAiKHu+ycX5w==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T10:00:32Z"
    mac: ENC[AES256_GCM,data:PY84B46aTAhzMf9v3eCDEBG8K50QqfLZriUMe3DlYXGBTZcgVHjzVJQeV1FlOTICbiXo0TzDikOKcec5r1mAnHyUbxr7ao6+UDfu+ZeRuMPQALHs1hq1hWQJ4d6LMfXh1TQgcHYhXSyYTG8mGOID/rcm4ARvU/uqopphcBx2+Jo=,iv:bT/QF3ftfp1msvaXEsZK1EF+05qtxLIvG1Q8+f0Zjig=,tag:LZOhfKLMddFFMvRY5SrZ0g==,type:str]
    pgp:
        - created_at: "2026-09-26T10:00:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA71EESEn7N2iAQv+NAERRu4tazPNPh27u8UPp9ezwTPuvldPFWZi5v+2pXBr
            DPcFDBIZy78mkH30BLAJQF7EyPz7MYew4WpBpAW+3hwdQNDuzkKYHwGczybeRDY2
            oS2TZDE77md/ZrHffiRpJ0BVG7GgVw8oIEJ90/qeMCUZ3a6dQrXb9iXaSGKi42WN
            aHeTjvgjCBNcyqvFeIZbMv/YOd/XStFae8Ouvx56r/6KZsfVXZrpvz0Vmoah+5vT
            U0HaauHreRgahf2P2oZInqEG2QsgjGe3mAIVxESywZfyqhLreawd3tGn8nEc14O7
            Ya9ZyLYcjUfYGHFHywhur3S89rBS+CHMt8evVhfDi1Mg7e+cpNdkffL3MIC+o7pi
            MMIOr5sahy5e94E2cukvqv814dP0X2IZqBdWVsc8/mEJc/Pg9N/U9zPVth4oAQwD
            KQ7EZ8IGwMGlMrd9/yCk8ou+yRAsUddXggTcDLneGsS3VBYAs6HBk3k7Vob2SmoM
            ouK8/sYV6TRtuy52b+Bh0l4BlKy8vXWnogPVvl+igr6BaectvYX+Jm+CZdzNpeAS
            jKKAo0MhZnFYjOPVvlVgluJ5+FjkQag7HAioDyeic89vkuZWPfcMC9PFipNF2CjI
            G1qq6B2Z8kIgqmLhvVLx
            =Agoa
            -----END PGP MESSAGE-----
          fp: 2D47B9C25AAD87860CC1778F7022B8F414F4AEED
    version: 3.13.3
