apiVersion: v1
kind: Secret
metadata:
    name: opencode-openchamber-secrets
    namespace: default
stringData:
    OPENCHAMBER_UI_PASSWORD: ENC[AES256_GCM,data:UJKTMHXZ6tx9lzLY15ydYaxVP4/cNr4Vt1ks9gXBMTOOKUx+21JLh+LdnQ==,iv:1ivOnerUhqF2HJBe5Hpfau+trX16vVZ1YyJIR8Epg+U=,tag:W/+b12Kf/HK3K23jmRMf/g==,type:str]
    OPENCODE_JWT_SECRET: ENC[AES256_GCM,data:LRQxV2qiLpQXgh8xVxl0NXPAoJJtiit/DTAQawwTwEHSEbQ3X8AJ+3XBsMaOUiLkY0yBPWsD6LarzibHelgupX7NxvmxrQOdz0epsWVJaSaFV++b3KY=,iv:EdNCIsxL3tfq7/dDe20aeDOdS5UTAiSgy35OJ7BY2OI=,tag:Mqyo+3SqiDBKAKMQjyTZmw==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-06T15:47:08Z"
    mac: ENC[AES256_GCM,data:wVUXntCIHvNubsn4ivaETW3QiIZHGRHJ3CRF0SYlg7SBAUTyhcozpIryrEANeIK1Vhnh/BVsWI76t3pD8lg2cayi61tYTTXn1rXKP7wZV7Jsm3Eh1JwVyG5Z20Nu63jplkG2V1fAjIlezIjikLCSegdYQvmTkDQsiGy+zyRhU7Q=,iv:X3q8yVTl9oV5BYJWDIhXRrixuYk5h1UETa/2IgB6VM4=,tag:IePlDBbMo4ADwDw7toTOZw==,type:str]
    pgp:
        - created_at: "2026-07-06T15:47:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA71EESEn7N2iAQv/QEf9qKDLyYcuDd3W5+JNPp5xFAWtEIFfM/rJXVXA0Jji
            nMRJ67esGA7MUeu45WahGq4dhq5YVONFZYOihBaGNHg6zFxUw9L+lUsEzQsdXUXn
            BJU+ztO3G5I+m4kQ/JYzhAaw0aiJJsQBWDL2imQ9ao4AAu1uvPRCcst3Jcrt91ZC
            JKWkioa2hml0FdCGI5qXBaFyFOwxkNLYXNDoW5E5hiHSqxPxahKE5xIasuYegbax
            14gTd90vn99MusW6yMz1aRncGSqPCwgXhXsw5BMQS9hMZO3ywzBD8THQjQqZaPq3
            4nlT+y9Jmq4r5DmXs8z8qskFZJu7Uz5Dx16SNO+/56IvavazpGtHe/n4lxtZwoCO
            A6tfHJtRp8mBZbBiJFGMWSWhrdIrKXVyomyHPgKUvdplHj1au2Uk1Ox0nHAj0ebB
            xQziK4HO4l78f7Qzmx43mWDEH4xJc7/1DrWsbvhtRQCAd3Z22tdpz9kSMWM8os47
            Ml5Lj9xBjWYOwFjcfCtk0l4BKrkIglVVG9tVsKBDmvxHyKVMxZMfXO/VPioX9ToU
            wzMQ+O9ocW+1W2nsqotan37SuJmqseOgvmQSw4Y/TAMTxCurpFP9y6J0hD9nAIRp
            c3Y/Z22dVU9wu2Bvyp3p
            =9vUZ
            -----END PGP MESSAGE-----
          fp: 2D47B9C25AAD87860CC1778F7022B8F414F4AEED
    version: 3.13.2
