apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: opencode-docker
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  recurringJobSelector: "[]"
