# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-4.6.2/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s-labs.github.io/helm-charts
      chart: app-template
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
  values:
    controllers:
      main:
        strategy: Recreate
        pod:
          securityContext:
            fsGroup: 1001
            supplementalGroups:
              - 44
              - 109
              - 100
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/arch
                        operator: NotIn
                        values:
                          - arm64
          nodeSelector:
            intel.feature.node.kubernetes.io/gpu: "true"
        containers:
          main:
            image:
              repository: linuxserver/plex
              tag: 1.43.1.10611-1e34174b1-ls305
              pullPolicy: IfNotPresent
            env:
              TZ: Africa/Cairo
              ADVERTISE_IP: "https://plex.${SECRET_DOMAIN}:443/,http://192.168.1.245:32400/"
              ALLOWED_NETWORKS: 10.0.0.0/8,192.168.1.0/24
            envFrom:
              - secretRef:
                  name: plex-secrets
            resources:
              requests:
                gpu.intel.com/i915: 1
                memory: 983Mi
              limits:
                gpu.intel.com/i915: 1
                memory: 983Mi
          alloy:
            image:
              repository: grafana/alloy
              tag: v1.16.1
              pullPolicy: IfNotPresent
            args:
              - run
              - /etc/alloy/config.alloy
              - --storage.path=/tmp/alloy
            securityContext:
              runAsUser: 0
              readOnlyRootFilesystem: true
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 128Mi

    service:
      main:
        controller: main
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/allow-shared-ip: plex
          metallb.universe.tf/loadBalancerIPs: 192.168.1.245
        ports:
          http:
            port: 32400

    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        hosts:
          - host: "plex.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - "plex.${SECRET_DOMAIN}"

    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: plex-csi-config-pvc
        advancedMounts:
          main:
            main:
              - path: /config
            alloy:
              - path: /config
                readOnly: true
      transcode:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /transcode
      nfs-big-media-pvc:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: nfs-big-media-pvc
        globalMounts:
          - path: /nfs-big-media-pvc
            readOnly: false
      alloy-storage:
        enabled: true
        type: emptyDir
        advancedMounts:
          main:
            alloy:
              - path: /tmp/alloy
      alloy-config:
        enabled: true
        type: configMap
        name: plex-alloy-configmap
        advancedMounts:
          main:
            alloy:
              - path: /etc/alloy/config.alloy
                subPath: config.alloy
                readOnly: true
