apiVersion: v1
kind: Secret
metadata:
    name: hermes-secret
    namespace: default
type: Opaque
stringData:
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:bisaqMXd3SrJDzClNjWvR9F6BWzq6FRdoYBSm9i2ux67/r1ogr7p+aX2hNtRrPCRV0BVopA/k+jXdvKuryGAAlIn88Dmb2tWZw==,iv:bzWNiP/jfBC1UxsjJtYjN54YHEbq+xVfxFj3uEjrW2I=,tag:bCX6ocDnfC/0yrUWvkcwRQ==,type:str]
    WHATSAPP_ALLOWED_USERS: ENC[AES256_GCM,data:Fd9FLdcR+RPkj8i3,iv:N757vGcBHePIZE5dIHdc2DDK9DvxxmSbN1+eHKzOkN0=,tag:Z3GRSallahd99dQmMsyBgg==,type:int]
sops:
    lastmodified: "2026-05-09T18:56:05Z"
    mac: ENC[AES256_GCM,data:HdjkNDnE0O9zHMFsfuSjjfDZU9U4QJ3VJuh4l+V8CFD0HZKKEs9atMezaOt7SUbpp0ZxV5exHemRCuTjPztvfbVVkLivcyO15AK5D8e+ka4c5IoA9nMV5UdOl+4KgPLm9pM5hUT7T2Mdgvts+4cN+xPOszzfe55n0XDR8brFKrc=,iv:SkEXQ/ai6RDs3oPeiyH2Rd59E5UlapPpARuDsa8LNzI=,tag:M0PyHCxd0FqpSJYWbj3tdg==,type:str]
    pgp:
        - created_at: "2026-05-09T18:56:05Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA71EESEn7N2iAQwAgJeVg+P5LtYVp26J6Il3wbUV+ibXe3EJrey42E4H6IeR
            EIVKOs4xZZKgGKAtbzyn7IPg1cwseC25+5jdB8PL/Bue6EVQ/+nFFzA99Fd/U8mB
            x4aEj3Bl748JaBqfoT3XcSpe+bgOPkWy6vLmIGMpDde9uxMg0CC+ueVrVh8vXK71
            R5Ow097FfK0EDfygkYZC/X23fwf05YX1tZex0w79ihYAdIkTpqup50UnWweTusLe
            vsH604RbUP0+XcL+sU6nO9OrUTbeg+476r2J2QiR3Lyz0w/QSx9IO/VifHF3puAQ
            EFoGUKj3k1K1a1Ra2JGDZEg4xYR4US6dDuHqn35A//Xp0mfOXkrw2vTKJhBw6VAe
            vwdh+rEI8glgCIvFyIeQgGh50KRx+E81e3EeNIktCqxD4OKipL5ltx4yZaNvIgf+
            ap/K+x9md3ow0Z58U+uSf10+4CGAqEP0pQtp/OYGp4rqiDSTEHF81cfeeoFtl1Sr
            hb8KrifjHEa1vuDO3uyb0lwBQwG1PRrMnHv4GQnI9+culgMdzGSOzx82uX+L8krZ
            kpalhzGs3KQZmV9nkcwgnttBxtcCwKXb2m9SRRrNzn+uN877Jaicv9g3SclVbQmr
            iu//sofb+clhl8rIvw==
            =cTwY
            -----END PGP MESSAGE-----
          fp: 2D47B9C25AAD87860CC1778F7022B8F414F4AEED
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
