apiVersion: v1
kind: Service
metadata:
  name: hermes
  namespace: default
  labels:
    app.kubernetes.io/name: hermes
spec:
  type: ClusterIP
  ports:
    - port: 9119
      targetPort: dashboard
      protocol: TCP
      name: dashboard
  selector:
    app.kubernetes.io/name: hermes
