# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-4.6.2/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hyperion
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s-labs.github.io/helm-charts
      chart: app-template
      version: 4.6.2
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
  values:
    controllers:
      main:
        strategy: Recreate
        containers:
          main:
            image:
              repository: sirfragalot/hyperion.ng
              tag: 2.2.0
              pullPolicy: IfNotPresent

    service:
      main:
        controller: main
        ports:
          http:
            port: 8090
      flatbuffer:
        controller: main
        type: LoadBalancer
        loadBalancerIP: 192.168.1.243
        externalTrafficPolicy: Local
        ports:
          listen:
            port: 19400
            protocol: TCP
            targetPort: 19400

    ingress:
      main:
        enabled: true
        className: "internal"
        annotations:
          nginx.ingress.kubernetes.io/auth-url: "http://oauth2-proxy.networking.svc.cluster.local/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: "https://auth.${SECRET_DOMAIN}/oauth2/sign_in"
        hosts:
          - host: "hyperion.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - "hyperion.${SECRET_DOMAIN}"

    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: hyperion-pvc
        globalMounts:
          - path: /config
