apiVersion: v1
kind: Secret
metadata:
    name: securo-postgresql-secrets
    namespace: securo
type: Opaque
stringData:
    #ENC[AES256_GCM,data:FyO1vyLMilx+7POcxNjIgXqyyiW6K3zNJlHurM6Rz1JdSpimx1WljOLL5fqN9Oc+cC6BQstSAElBbdOPwQalsFYOsgH3osdi,iv:o3f5KQkJFKOJp3Jhm474oUN9DIbzmyFcWZYeQsRTw3o=,tag:BEvZRuTav2RUFvMf5yqEjg==,type:comment]
    POSTGRES_USER: ENC[AES256_GCM,data:Sl/NUFLNevdlJYzoalClRfhc0/gjEfDPmeN1TAXd,iv:xKfa10NHcaN3ZaDlm8E9O33xXwzmqh3g4vam7ROGHew=,tag:ZPpVOk88faaA2FXszEk3pw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:As0ML0VD0VFXzWeb0x27wX8EAzx+gEDAQ0RTm3Egziw+Zyys,iv:YzO33UGwzqEs0YQhwUfSV/txyIe0d+MxZS4xWsPtKF4=,tag:4WzWJahoSvGYxa327qRIOA==,type:str]
    #ENC[AES256_GCM,data:xh6uRu9z6z9QLoMP4BApIFq/Hfc6HZaFQLGRpB7oAhlbGHx9ka7+Pl2XQELsjWShB9aiek6W07DWlQOGFpDLm01c8g==,iv:Ch5uLxf89NpfJgpKUVnZykbz17O9OVfWkRcW/cSB2wY=,tag:I1BRPkebRFInRocrdgrbaQ==,type:comment]
    POSTGRES_DB: ENC[AES256_GCM,data:LqBMfv0x,iv:Mol5KmzzS8VpYsRa5bND5oy891uQSx+NYJmrUIYte5M=,tag:LfbDyonhs9HKJx6c/JN2jw==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-20T20:07:13Z"
    mac: ENC[AES256_GCM,data:gZj38RaJ4vamXQEt2a/z4egUS5ySLuq4JHazRpvf7kPXm+JNzosHSyXdyGVFPmTwrjDF6VLOrGRZovukHjtFwn9bP15Forjt16SVTmONWfBbF+Zn9c9TjdIKRxNaa0BcYHwZGg9UpoeEoPn3dc4OI0ZlYs5mjiLbbiBeJLK4QwY=,iv:sfW0IKIsCM1IfenGp8ew4sHxnCCJmkfZ4+diu73Jhoo=,tag:vhJwtIc4Nm216+qlDtd3wQ==,type:str]
    pgp:
        - created_at: "2026-09-20T20:07:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA71EESEn7N2iAQwAkSJZ8mWJ8NnCy3Y79EuZG0YfXAjZeXNd+mPGci3LELgb
            g26Ps1LMHTiYodo5CGpv2ZG2hCksgUDlkWj02de/JRniBHsv6kq1LxCnorWqJH3D
            vKSNm7E6JaWL8R0JgiaJzoiHoB39ASPe/7QQW6oyet0aPHduUH1xP0CvDdyPWpnO
            KVBz4IhbGzC2tzXUNsMGXcsIwfZ6cKEEJKbW55/Ft5EhYU3aWVi6fPC7BVT/cTtT
            ULzNNfFSa5P4/Ml5ZiYq3GmlvqBVkr5MTzLR1WXXTt6OvaRo3mXjPbPBo4C8JPRt
            vj6NQLVMDSyOk1DjcMGU7Ke+byFnoM8W66EJkRWO//Ksdhlv0TLZqhnT/19sQeQG
            AzGNq/j9KGWYUQi6ur4+iP5ZLN6sFwcbD4M828QKEWPxS7mcEeGkp02kT5Fd1p7N
            ygB4VXM3mEbJ5Xnd6FuZt+zd17Bd2eZUeG2gsObyUQnrUeeiRQtTSvqYn0JkYKzi
            40KQLDuhE66XalFbBCRr0lwBdrqcl/w3gAjCzave06HG5Va2ieXrFZeZnqYNohF7
            eHhKpZ65S8BdIg41qBS53FD1wZkac7brpDMdTAVP4Dq+8D41dtexsBjdC5LyALwY
            Sh12jXZfQAPpje0nHg==
            =Pxpz
            -----END PGP MESSAGE-----
          fp: 2D47B9C25AAD87860CC1778F7022B8F414F4AEED
    version: 3.13.3
