apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
    name: ghcr-login-secret
    namespace: default
data:
    .dockerconfigjson: ENC[AES256_GCM,data:JObVcfbgBqs/MevbjIosnM+PFJogHqGdWk8PUdl/F2UQzsbT0Uj/f9ZR0TGuCr+WcCRqxdcThaWF+helQH0vJ6Y80GZt1qcNx/ZepV/juuRR2BgydTh2Z5CifndmNVgVnaO2mVt1uHu/BUNKRnGEpG6HFh8uFgIaci1b7+76DlYh0/zO/IYUD6zY2fC+T2dDrJsuQv8cbm3H+6o7zsUlHVi1w93omdPTteMVvuRrzSEpUoclvGVzEkulQJsy2A+R1BJS891EqWPklU9RfCx3HUeP5dhCoLrENKpuxj6LNIM66lJQahDnGuVf8Klf1cU3,iv:IWcnR1NVTNMUKukbe6UZFqtlif5OZC5Du1AXOFiJJE0=,tag:7FoGJB9iYAgnEPiWLVmL3g==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-04T12:41:56Z"
    mac: ENC[AES256_GCM,data:f3wAKR/knBBfH19uHDjc9AmzSHlY4yRH35/wXkWO46ZtsVmlD1DZfZVs1skjnwyTZNtnO8uKjnf7qGrdC2cNbRrDxauPUVfxfBTyAqX2+hN/pfqA4mpOpJZFCkSLryNV96i/TYxCQmeNli5oIsdM4fkskLiIT1vnwO4s/Ws9nM0=,iv:u9Di/ff/8Z6KfEza+8ObRhEoMTFH7NMfx3O9O2lc0jc=,tag:ANFkcGvW26pwNSF1Ivg6pw==,type:str]
    pgp:
        - created_at: "2026-09-04T12:41:56Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA71EESEn7N2iAQwAoDTUZTfgb5gLWU3DY+d0kr+Dkw6exMXnnYimzd7NJmFE
            rG0I+0l2se2wBmfi5yyUJlwuYc29EflkNVV3vZEHZjT5ORpNbAcBRoqIrFd1kV8k
            V6GIlAkyEPfPO08BM4uFVUeQ2pQ1VucxYBiD7bs5rn7FP3n/8iy3DSMllIZPabuN
            RCfPxLwyf8JzUjInZHhK90F/O1JOftqHJCe1xRoMPE5i8BhFnMD3GJrd4P41ffrP
            FFvFYWA+jeu+YqQ5KjXKan7VDUEmQZdz8Hw/yFkC15md8nQvmni8mvHrc62Mhr6l
            fP/6UnRoI7sNtoZ0lrj0PvT4+NCf/w65ggaPwMo+JvACHB1vgHlvU83JrmUwauVE
            63SYYlLWoDt7SIMQaktU+iqhPvrJijo1u4C6tpJDYIeMkrWoQIDcnm5fwsVDVLYG
            Zy+oXc1ElOrNNwvgyGBjh0T7SnfQMxbjrTX2yMZpEQbTq1A8i6FOAfPPB9gv5dmI
            KkI+zGVkfrfFKZi5xbEs0l4Bl/DK1lFg/UxCm61wNAzMyoRUE6NbnMK+RtVx2HdU
            ogcQJOYV/TeeTtqXcjGANFv+Gba5eBe+PQo2uFa0BKOchyxSxWr041/HsUHRNihs
            hcQjF4lIzetMqB5U6u8M
            =ERKr
            -----END PGP MESSAGE-----
          fp: 2D47B9C25AAD87860CC1778F7022B8F414F4AEED
    version: 3.13.3
