# Replace every placeholder, then encrypt this file with SOPS before committing it.
apiVersion: v1
kind: Secret
metadata:
    name: we-usage-tracker-secrets
    namespace: default
type: Opaque
stringData:
    #ENC[AES256_GCM,data:uxjcLniCMtR/zN4i2EzChdLsfNTBGs6U8p9csUOxQJ4CQWcAKSKI2oAfNgqDFIIMx2cOVfXekLWW9iTSYCmVwERdcFpAJAwlZfGE,iv:g3OPjrkFHkIcjKgkd5H0cPsIZJ88RRRPh1ZbB9Fp51s=,tag:kYlhvIYB50d1ZoEJOFgWTw==,type:comment]
    WE_ACCT_ID: ENC[AES256_GCM,data:cEWkYY3FjVOmFosM,iv:oHHRIJ0Ri/skwGRCjrMME0ZMze1EKItDFrLbq7RsZew=,tag:nbWwuiRlEuSIeLlnckavrA==,type:str]
    WE_PASSWORD: ENC[AES256_GCM,data:sN1iPhurVsvmhGlIi55jzQ==,iv:No3PAWq7TBOkK1vBPfrWfyIlJ1A2uEslAKnQMRvFfG0=,tag:+x8TcAwXjXQFkGsXJCpqYA==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:93yC6cU4WpxRQqFGwrL7+c/DcD+BT8Aje10BWX6LwT80RMHdLkUfjEFfCzqL6oaPitiGqrfdnSqmwGWygomsVAVp6b62VYBrKg==,iv:N+KQAr8C4HSLBAo7U2Tqap6ilpMfpxoyTMppVNHMX1U=,tag:OWygPHjsM3iOvlE1jVhFow==,type:str]
    APPRISE_URLS: ENC[AES256_GCM,data:iLB+U8RSlVqmQVzM8iq0fU0jJPu0hYFokasZUNRsB5Xvt+mG82/0fASwNnGmsWGDT8LZfrJEJfnBRvBF4ECTnfkr4sYYExs=,iv:cvjkhcV4kltsukZQymZFjTlmN2KUxDbpabvgRqSdq4o=,tag:j/WaZNFr6fC76mvXjy0jPg==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-21T13:30:23Z"
    mac: ENC[AES256_GCM,data:QCoMLgQegZWuTk3498wVX6XJkWqpiYJi9GEtpfaH2vtOyRa3bKffOTjP2zxb46MHh99lIBQWUKyQWrbaQhJ6EpaIxXuQhd0Osu4iIBVViSc/osEgfGFDY8j4iue/cwqN4FL4yykQeHd7l0T9pI37h5IltIlpB/CICZ6fhyA7E1o=,iv:ueXbbBqnOmXyyskXs6Xt7ZNlKcDjGGMr3lzqG5xMPWs=,tag:7U+717arZhZmxmDzJOYcgQ==,type:str]
    pgp:
        - created_at: "2026-09-21T13:30:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA71EESEn7N2iAQwAjk1CDe57QcqNk+S4msH5kKB2YYCkCk4dWsc7ekexhmp+
            FdVr+6D2fVl3Z2QMDfvJU4eKNnKZ0xRTVWJPAKp5eBhSuJ8nrdkymncpNR9Hx19U
            CTJChOBbBeKXm9qZO8XBbDKFDUssx78vCpWzgcgxnJ3ruNJHjtUrA3F2oxX2lsdx
            yXNrH5k5nDPXGRfKlu98lL7Ud2SfQmk8jk7e9ruGVOhNws/Mo3G9IS5Zsl5iDYNt
            q3VuUebYy6A+hiv1MWGLCN0qF8dk8CTC5p8EX+KrfAM1Yt6WjCpN6p0M6TMtCP8m
            GDNWt/3mf6coGfKGMaDtZ03bbnTC8blL8SMSJ/x3U/6/rywNLfmT6CDOk3729HMt
            gfKeCmcqS7pJ/8tKqvDBNghKMKBngw1Vk7Y/U2c2MBqlW1Q8pWZB0ZZSRytD3zHC
            EXXsLpYzCcl666SfZ3ROKztxUtDa0WDHP6g4Yqg0+DYcXfsixEtP8NlJOHgIbFOU
            C9ELpIFYzpHR8Szooul80l4BB2SOf4wjUA6mICcW4TAkP+ll0mt06sw0EhJ2+z28
            eD+7+08/N1gcR3ZnGwqUbf0jO9vSbb0L198Z8okknSp+FyZKI02YYoVjyG7hzn4T
            owyFSUXYbFbqrBmzJHWU
            =XpD5
            -----END PGP MESSAGE-----
          fp: 2D47B9C25AAD87860CC1778F7022B8F414F4AEED
    version: 3.13.3
