# Replace every placeholder, then encrypt this file with SOPS before committing it.
apiVersion: v1
kind: Secret
metadata:
    name: we-usage-tracker-secrets
    namespace: default
type: Opaque
stringData:
    #ENC[AES256_GCM,data:JFk9lSTh6EVCRwU/KnAQHiliaWfSMXqIBAXzrlRf6+b1Hz+XODubCoIGUstw2NNS7rWDzfDn/tVbIi6PmogN1/ME0qLzOO2wHyvq,iv:qKepj/ZORB3+sTguA7UK+4RFmViGIAmpunzJ+ShsTc4=,tag:9o2yb3qJRCziWzvuM3DP8g==,type:comment]
    WE_ACCT_ID: ENC[AES256_GCM,data:nS4b7wtJoBFY/Std,iv:2I5FZ6IZo4ns8YruWJnbAnY4/6xjVu7j90mrIoluJK8=,tag:hCBgwc4nrvjHC6w8KtX9lA==,type:str]
    WE_PASSWORD: ENC[AES256_GCM,data:hX+zFdxfDLJQ0uvHahGimg==,iv:G/as1dgMA+P5D7hFAQETmYsj1dg/ahKOS0vDorfn7Gk=,tag:JxeuT7X3/s+4pTzaJ8EfbA==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:Sujx1gbMf8UttDN++I3bcE3WPpGwF/7ElnIOwoW4uYazbSuHO6WTQRbCjUV21Lt0w+GTTIQxvz0uuzt8mA3LLu/Yl6C7oIr/dg==,iv:UVfvgEwxrdw2LoGMUGB0jMlKevOh5neQf0PnNwcEsZQ=,tag:War8tz3kbSdnqM658ewvHQ==,type:str]
    APPRISE_URLS: ENC[AES256_GCM,data:3XXmQ6eerlzn7V2fEltIcuFYnlbepnChxmVCKf23QK7hwkR1xFu++QjzI0Jrf5C+hLfPExmgV7KJ3Q==,iv:Ki5L4StvqGDhtqj4ENQTnEHNR1WoJ4+8t8I1pGd4nlg=,tag:cwc+fD7b6SfGVLDp655Mkg==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-04T12:33:16Z"
    mac: ENC[AES256_GCM,data:Bdo9iedsxfJPFGVdOPaUG9TKuH8+WYUqfThjU6li8raBxh6Qo7L9Qn7cWeqHTNWxSXIH9DIA/S3goHNh2Fg31EeIRRGOjGdJURHA68MsHFA9A425sKtzNQsNTNZeCw/S/WgTb/dUY9o8cSSfYZnUzc/PTu1i5hPBhrahC9a3w5Q=,iv:Z3tLjbXYmD+t2HFDKFizDSoJN0+R3ySeq0JIktEqQfE=,tag:3O1uI+m6QpusUNFGXyyu1A==,type:str]
    pgp:
        - created_at: "2026-09-04T12:33:16Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA71EESEn7N2iAQv/QK+FGj+DX2jOGy8Pj909tWWNxgZ6e8y5bPUcA3Oc1rKY
            gKx06avX29+QpK9RlcNp13nMba3OQ3AmvgQ9knL/deJLi1M8LmV1sdXpH8AUeQU0
            qoQ30bgEmRpbmrdrmq1x9RCxOalafmz+5tTCRw/8dTuIU5Bxlz99WHiXW8MZzOU2
            mPGR5BOwKHygMnyheq5xS1XvPAyLRxtMab7Cn03IvVjgjdzRSlI184kn5tEaKlAg
            3WMjZUUQQy5H5yhEIEnqgtjVrdfmmQHvNCwZ+ne+/xfQpkQhaAn2uzeB+sDOLnuN
            lS0NPlBbCdi8WuQ/K6bKW19wJCEJje/eXTuoOuw7PhF4uRW4KhMG9E+SEhhwWRjc
            83zNiIt9WS2l1dTNN5z1mE6yyd37gQOm1a8u+ITsQpSMxWflAyBgIp9dBmVzRO9K
            F2KXkasN2me/Wd2yBV7M5wI3mzS/Yn69TET1Rjz8bYXg4FuS5DDvgIXdFJGWEzhP
            w2/CCmXyLBu9AamDHwgY0l4BFi27ioyNGSr/TcmaXC4HiJJqKoh2Q8NBrch6ttty
            Jt7egJVrd7bWqwEdOHMk3gnrey1dEu1T23KZCJU8TTo9GWnmDiMIasucFg3/h3B9
            AkSTaED1XnUSOUI70mem
            =CQXP
            -----END PGP MESSAGE-----
          fp: 2D47B9C25AAD87860CC1778F7022B8F414F4AEED
    version: 3.13.3
