apiVersion: v1
kind: Secret
metadata:
    name: hermes-secret
    namespace: default
type: Opaque
stringData:
    HERMES_DASHBOARD_BASIC_AUTH_USERNAME: ENC[AES256_GCM,data:nrWKsmlb,iv:mGL4sIDkk5eSFiQdtgDQvEO4S1/L8ojklkhmd9eKktY=,tag:XrMWl6z2H6QRWMwFadA7zQ==,type:str]
    HERMES_DASHBOARD_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:+1iARi9v0Z3dJyrikLv3xoQeXFYc035+wa0xxMXD,iv:SE1tw9xtxLAwUfo/Wm7IQaTJp8jtf29jdtw0Zw3QchU=,tag:MGJMrJgCCTN8fVyhLdezhA==,type:str]
    HERMES_DASHBOARD_BASIC_AUTH_SECRET: ENC[AES256_GCM,data:f8A63cuVKOfgKDg8fgOFBKh/R8sUPL+p8XPTnyTglg9mTDovzVUIJGG/Ij7by44DJ6guFbV6F2I1vz4sI7Y8OQ==,iv:k1I0DjjX9dKHs3S+W8tv1v5Y0EDwmBlDgZsHsKpGla0=,tag:PWIo4iPp8jv4twT7q5vj3A==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:Lxh0XcX1vkzxOAKqM+GTklNhugX7P9Q7rnEOxSpAqFRuMkq3J3KZJ4uHsxzNjpgjs5+Zo3nGtva/gPMqJG2KF8OiR8EZBL9DOg==,iv:upPrYzhCukuc/MkOVu7MK2VUpbdODGm+TFE/hhJn7hc=,tag:m2QuYBXFAHPeRQ4/iHSlSQ==,type:str]
    WHATSAPP_ALLOWED_USERS: ENC[AES256_GCM,data:iMXpPw8leDHAfZjq,iv:AFSUVRldClAGkauxtntHiX43GM7//1MWyNMQlLVvGq4=,tag:a/OZPsUuHDuv/DjVCj+bqg==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-03T15:00:08Z"
    mac: ENC[AES256_GCM,data:P+5z2dSuQy6R+XScBOx2H9z1lvB6Dl3k0Uv7r9l8OwKUaC41BFXBqHVEOALDP1W8REl9Se+3eGuEnHzoWSSXHfru/M516IEC1bVn9p8ya5UcJywGKSkKUStUbk914h3uL/yqzi1ZeRU7TVLrTA58eX/+l74otlVwko3vQc+0KAQ=,iv:R9IRp3yyqtyBMPrONcREV+oWoSRxr9PCni16jZ7dYcs=,tag:ObGEagx4pv3H2J2310Abdg==,type:str]
    pgp:
        - created_at: "2026-07-03T15:00:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA71EESEn7N2iAQv/WQ54BSHoKc3P6ZJ62WgtZHL1nKl++N1DipxBWRJs5Wmn
            3+JarlOM1yAnicYbUigqV8uwvzTs0GLgJ+IwcsojEqpJ1L39X+5W24QaDqPriZOx
            CzRAF9VtKmR5RDgvCYkUyLcSsPYZgmQRMsVeideO4KvEEL0X2FAVtaxEDmnuhpYK
            gPnzKUi3wZ1B9V7XYbHI1oCATRq4WLa/YU6Z96WmwDsFp1FvlxPBiBaSGP5bQr9n
            nQqP00DV8lE1PKN6YZjgLWp5dgx873uclcNeokBzk6OCKIhtiC+rzKtTi/AHkSj0
            km53eRsLUqsJcj4+u0MjKswKkLLu1URR8LwhKv8y/5ij9mzO9HY4/vxHdJvy96dD
            uxYG/BVnADt5EgeSU4tBVQnOuxyj2WDlkcfsFXIAYOSKIZtdNme/7fSwy2V00dOn
            BHe9bFuFfCqorNJC+SN/mpbCirp7cVhPbE7nvMKC8NsJBe/5JxPUeRSvSTXNMfT/
            VS0dGbrPqX3tUW7XOXeH0l4BKSWQ6gLiJl01viAeV2exAqw9y/udLA/4TEIt/iiE
            hM0ZhxMVNjwBVsuWtXFyvP4ve852Xl1gC/PIaxy3IF88VP5Bg3Xpa67I0qJI5wY3
            bqiPicmplpw8VUUqdVc9
            =a7tj
            -----END PGP MESSAGE-----
          fp: 2D47B9C25AAD87860CC1778F7022B8F414F4AEED
    version: 3.13.1
