apiVersion: v1
kind: Secret
metadata:
    name: hermes-secret
    namespace: default
type: Opaque
stringData:
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:fM2X0eEYAdRsKL3c900PnUXPSzTC1F9x8qj6cGeraJCF+Y0LRWwB/Xr1oJDA48T8cjeoPYduUX1ODlF852fHuSF3NEI7cjRTPA==,iv:1JuP1Si019WtowZDZm4TRHs04X4Cc04g32HNHqSiRjo=,tag:FkZhZdmMcZF/7qJ2+lsOcQ==,type:str]
    WHATSAPP_ALLOWED_USERS: ENC[AES256_GCM,data:Ct9rfIHcKI6dVbEr,iv:pvMNr/3x29UFVejxklC2hbtkLgJJmqHTBaLtlZMiu6g=,tag:p/xTr7UW3JAaylhyw3GQGA==,type:str]
sops:
    lastmodified: "2026-05-09T19:16:14Z"
    mac: ENC[AES256_GCM,data:CUxOHMxGdxBfeKL5XGdxwfZEiLSU3kIdPQIi+soXQNtA20t25Qbbq1IVddQ3uigx/MT+RqxZPiCRG9h58txL8fwlyf9YBBcmjWmDZGRPUxXbTSzQSzq30royuPIOnud9jwRPzFNC1RITBXmsa+ALvKRX06Ylg1adGd6yRxRewpY=,iv:KyOfaivpF5fJ2mX05OHWDUtAOZVlXQBgQz12Znuhx+U=,tag:eKzBqQwO4SJux+ZIIH1FQQ==,type:str]
    pgp:
        - created_at: "2026-05-09T19:16:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA71EESEn7N2iAQv+J3F6fmJOpUt3gBKI/VcoYV1NT5noJ9awrQGYWrOoXzBJ
            76b93radZKZUwX1Xj8yjXI/Q7Qkg04/je+F66pUHQCbIpCrgj9lp+wFlY5j+Qdyn
            4fQIj/Mz9UOOUOf869RUR6eY0H0SWSMQau+NhT0Qot4ZtQkthGzPJC/onhgVBSBS
            x40OVgFXepyEBAYUHaZAQ9jkbqfv90fCUb9vDVjGNgr7lwRyf0c3YyWY97YOPkJl
            asFSmdROa93qKnGk0T4Hq8/UoJlLphDzvK02lSP1i+trlCjF/wT0B7FdLE6hqiyX
            kd3bYRhA5bDbFYyCL7MhAS6Z1+6k+wxWm11aY1DtlH9pgfZ56QLbTLJ2NvoQACa8
            JC5t1TRPlX832wU9vAHN5/TwULmwKpPitqJriqTzZthbqQJulKtfYAOXGigFfMPi
            M5PJnwHx0UuHIZ7sbexHr1yXiqAhamVygMDAi5gC5OVjsokQ2ywqETBSt0LSNfSP
            0FMFgDzXDZ0PI7acl11C0lwBhtaiOPALoe7ZwhxnQ7xdf+9WHVK9LnXYas68HYRy
            txL1dDhtCQkie3MjCD6ZT3ks3J2ZvK2W9LPdM9zDVZvQFQIvMKKn2XgJ7G/qHBGj
            giRqPPhzzi/cmF1WCQ==
            =lkRA
            -----END PGP MESSAGE-----
          fp: 2D47B9C25AAD87860CC1778F7022B8F414F4AEED
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
