apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  interval: 15m
  chart:
    spec:
      chart: ./cluster/charts/rancher
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  valuesFrom:
    - kind: Secret
      name: rancher-bootstrap-values
      valuesKey: values.yaml
  values:
    hostname: "rancher.${SECRET_DOMAIN}"
    replicas: 1
    tls: external
    ingress:
      ingressClassName: internal
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        memory: 2Gi
  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: Ingress
              name: rancher
            patch: |-
              - op: replace
                path: /metadata/annotations/nginx.ingress.kubernetes.io~1ssl-redirect
                value: "true"
