apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: descheduler
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes-sigs.github.io/descheduler
      chart: descheduler
      version: 0.36.0
      sourceRef:
        kind: HelmRepository
        name: kubernetes-sigs-descheduler-charts
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    kind: Deployment
    deschedulingInterval: 5m

    deschedulerPolicy:
      metricsProviders:
        - source: KubernetesMetrics
      profiles:
        - name: default
          pluginConfig:
            - name: DefaultEvictor
              args:
                nodeFit: true
                podProtections:
                  defaultDisabled:
                    - PodsWithLocalStorage
                    - FailedBarePods
                  extraEnabled:
                    - PodsWithPVC
            - name: RemoveDuplicates
            - name: RemovePodsHavingTooManyRestarts
              args:
                podRestartThreshold: 100
                includingInitContainers: true
            - name: RemovePodsViolatingNodeAffinity
              args:
                nodeAffinityType:
                  - requiredDuringSchedulingIgnoredDuringExecution
            - name: RemovePodsViolatingNodeTaints
            - name: RemovePodsViolatingInterPodAntiAffinity
            - name: RemovePodsViolatingTopologySpreadConstraint
            - name: LowNodeUtilization
              args:
                thresholds:
                  "cpu" : 20
                  "memory": 20
                  "pods": 20
                targetThresholds:
                  "cpu" : 60
                  "memory": 70
                  "pods": 50
                metricsUtilization:
                  source: KubernetesMetrics
          plugins:
            balance:
              enabled:
                - RemoveDuplicates
                - RemovePodsViolatingTopologySpreadConstraint
                - LowNodeUtilization
            deschedule:
              enabled:
                - RemovePodsHavingTooManyRestarts
                - RemovePodsViolatingNodeTaints
                - RemovePodsViolatingNodeAffinity
                - RemovePodsViolatingInterPodAntiAffinity
    service:
      enabled: true
    serviceMonitor:
      enabled: true
