apiVersion: v1
kind: Secret
metadata:
    name: openclaw-secret
    namespace: default
type: Opaque
stringData:
    gatewayToken: ENC[AES256_GCM,data:ifFORtlG1WYv8+/M54iv+4/VLJ6IaeMlW4PvYJLMpNasiGNXkol3+9h8CuFd/qDc,iv:teS2je8NjXcAMJLA5IY9MDNM/pqOGx1dmlVdD7cZknQ=,tag:sPAAv2iX4ewZzCa6zbZBPQ==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:x+lLfFWZOaWxIlE6GdwzAvql6XkG+jFoK30iQH8viz4T10Ca7VUkw2ZKcWwYhYTs5YKtWimr04NsAJWV9Rq9GZtFo/wB5CuqHA==,iv:7d5vre9grXpbFEtWFWMD3fyo41JY3hvJnbR57jh2HIk=,tag:Rq3odU81bh5ABUEoHAlU0w==,type:str]
    OPENROUTER_TOOLS_API_KEY: ENC[AES256_GCM,data:mbWO7Vvrq4SMEsy/E4NK27XFPJQTPWmeP0vG14D5Wlo3ibFHSAqVxeiCyHSEX+tUFWD/3LIHiWvSXetkhIe4PQxYtsUMNN3NnA==,iv:QISV8UtuZ+TLRnt1M//S9Z4PUwMMVP0qNbqbXdEXlrI=,tag:WIJ5WefvyKqcS90SWg1Pbg==,type:str]
    GITHUB_MCP_PAT: ENC[AES256_GCM,data:ljxQrjnPTsbm3z8u1dZHxkrp9dSTBqcwyXcPrbyYV8bplLZHKg3ofQkh/3yZA9LGIs35wCfoXquOhyVr3oq3t5y9VSonODVxcVPYizi0T99IJGPvqC9fz6BrENqz,iv:yySdYHjB9pTz5Lv8U4DfeKZ/SHTvYoi1vAJJpyWruMM=,tag:Nz6y5yZLkRbOs6gju8ql0Q==,type:str]
    HEVY_API_KEY: ENC[AES256_GCM,data:H+vksLbKDlmAgTTG1heg/sPn88SQ34W6OOuRlTAWh5d4T1SL,iv:6BRqBlQTecEdruBenW6af/UewB1N1JR0PrYM7jMc0ao=,tag:Ke13MZzF3YeY3Y9HfwMCdQ==,type:str]
sops:
    lastmodified: "2026-04-15T18:48:08Z"
    mac: ENC[AES256_GCM,data:jeGwJNvEE+HtCS6B+CorVgQCWiiwimrnrsN0ShTWCQgz0PcP9GuwPOEiqdQu4xldwnQ+iJmQEbIBKNElVJ71uOypWc07xIPTnqEV548fQ0QvRV+s4u4USu4i1iTT0zdEa1mDRd7T7aab6R9UHAXSkyaOyMt0M3KAtT4fsrACXQ0=,iv:IJDGCK+P4wG2T067lF1uSpoa148zmuIivLgQGtoC4qA=,tag:qNsQgXUZzQ+ZeHt83zberA==,type:str]
    pgp:
        - created_at: "2026-04-15T18:48:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA71EESEn7N2iAQwAl42jFP0G8mBnB3pK4VI/CAWbd1+VITxAk0IQlof7BvzG
            moSU2F7CIsddtJq5eODxM0ZOrICWT5KI8yFSODAN6lLrhpHuK1gUld6t4RYhtSGF
            1vpgQ5kbYDIbKpy4HjQJQqXitjWEGiOiwP836MuL1/jUCakIpCTRr+Ui7ao6Am9K
            peAqmf2oPAFp1mzYmT4NYRCU3dL/PumsUiuh/stR1HDsC13Fc+O5MMVZ1sYcNXBC
            rn65vLzpQRnDGxuqB6WPIosSLW8m4vqHcXijTOkRcd1J976fQ7eCaV0Uy1LvS9EY
            smvZDwolQbPBHdQKbFdP3yvlMMtCWtZBX95JHZK/7BWvOW4raN3tqKDCquAVht0P
            /bPnL1Abt5RQmdzPWLlNuBewxPPmosoWwc9Twbmk/cLqaM0BFvgfbcqtHjcDyT6u
            bY9m5Qnc5VNIlyjRZJbX8N83VIawQmo1O/x6M6U2S5xu/Zqgf5pCrvTvOTIO7v27
            1twWJZoqvgK17J+39Vcb0lwBbben/QEdlWjjYSnL7CElEQDEuLxKmKGJdlWTkKS3
            TowmaKjnTn7/wzclztrU+7iELYO0PgsfBqHTjK4Izt/blsHYcAZ9Qmn5fa7lPv/l
            FKLLVo3rchB24PVgwQ==
            =+7X3
            -----END PGP MESSAGE-----
          fp: 2D47B9C25AAD87860CC1778F7022B8F414F4AEED
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
