apiVersion: v1
kind: Secret
metadata:
    name: openclaw-secret
    namespace: default
type: Opaque
stringData:
    gatewayToken: ENC[AES256_GCM,data:78LTHC+t1YVhKJfY6Re9otoTWztQRrbq2ltOVGBnPWshIrqpzX0bFBfjZR0W+vcP,iv:Tl/iJ+GCe7GW9muP0df32lZMzQh9K721x+iF8fY6K28=,tag:/YstMtZXIn/aH1tp3u7lEw==,type:str]
    PERPLEXITY_API_KEY: ENC[AES256_GCM,data:y4myXt6A3mO82PT7Nz07EsJSMsuWs31JTDyKNgCSvSotGo56R9zrm3KB3wMeMkkvDjYUPBmsWSFBxXCrpA0hpuAvmhntIh39LQ==,iv:jSqoP9JOX+QA5qLzpaM9dkjSa03oAM4ZZrwA8R8oKEw=,tag:lqNyMh9erR5JsiBPwG/UCw==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:+QUnfCXdvymmwKmwqteFp6NkJfTz/YmLhmIFIRlolgcLUETdMbBsnKZ0fBeNWKDdUtuMLLAWXv+bJ8F949E1QOuZawmpsaOHyw==,iv:lJJdIXeFE6L/OFylzn6Z5iJlP9yCQx5xr/GBaVeXkdc=,tag:XldnrPyUd1OwhBovvXtnwQ==,type:str]
    OPENROUTER_TOOLS_API_KEY: ENC[AES256_GCM,data:rmCeSm7ZxbCEXqMvUYJBGo7VhQ+WuTb13nhnFre2/pwrcx+zSbELISaXf/iAJVNsV7/SUMD079Z6aDDPXfMKcrupOdpuh2gICg==,iv:Wa1dw17KEXnqwmKgB7cHiN22/jBlTLzIvt+A4U+Iflc=,tag:MrsNw40qN7My9tIEUe7UIw==,type:str]
    HEVY_API_KEY: ENC[AES256_GCM,data:I3TQ0aA2eaz0Fi0QKTB2jeO464om0X90DYKxBc0V2oAijwLl,iv:t8QHRFlezYIbvklyn8ZNzENo+Dbn/5+dcGq6+pEwog8=,tag:oYT5EJHTW7/EFPvzzMBldA==,type:str]
sops:
    lastmodified: "2026-03-25T16:34:59Z"
    mac: ENC[AES256_GCM,data:YqPfNtJSPe7ZaL5a4aLB8kCmAKJIm6VvlxCxMA8gYtCzODxTT2Q2gUCeTrVs0RmAa8KqQkQUGbf9iTgCKBvaDZ/La4ImUycwYbLdoYHf8wjXsb6sRWfOSko0MASuA3A23qS7cyRbrufrqsVkIo4IxXFK6E/7TLUpg86J09fom1M=,iv:nmr87W/elKj8pnHG45J6FR5UpUCDUitcGKnFxVmzywE=,tag:aULQuTBsep/vOnixOPtrcg==,type:str]
    pgp:
        - created_at: "2026-03-25T16:34:59Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA71EESEn7N2iAQwAgPeljjrqUad3ON68FIctGJsmfUTE2Sr3EumOldT8mE3l
            I01GDIlFUedUnc67ADDoufQMrXqj+/3Lux4hCrpRRNFlvkm8QFA4I9Cv/OKQpcI6
            cJu+7WAerUVcdCHhOxCqLwxZ87Xfze8NQOPtkQ7gCMTVD51JxiWN5qMj0wZ4yinU
            1f1RQsK9fLouxDnY4O1acFnYxBOrJsZdNNz7ZGY5DX1QoNCiJ7t5g6YskZKloH7E
            dnrUmVDQpBkf8z401o1JcetQULJzV6jlttTbIjMmx3iZFACdZmVcvZ7qh5HDdIEj
            aiGFajptJBpFbF1ws8P5c6T+8ttjePvuTo6Ir6iLcFJAwcHfkoHSjTKhcmhNCmE4
            DfHWh4l550GetFD3dfEU/gvtibhFkNJG/RIhiitokKr47U9NNmhfwba5lxdhMOXk
            9GvEBDZR4I3hHMk17c/oGnKe5e9NuNbpwHPVBU7J1C5eAjNAKXu3j20P51rxiMzi
            tZoViFRjwMTra9kNUgLm0l4BaCDGKK0LlUdhLepRsaJzwcFTQu1dC11ZmIcIX4dE
            o/bBOIJr+rpSvDck/w//q9Sq3kMe1IuOFHL8nh89+IwpZDb+26gc7w3SYz4nvu1J
            RIAZXhDYRaL2eovgEJ3t
            =6kxC
            -----END PGP MESSAGE-----
          fp: 2D47B9C25AAD87860CC1778F7022B8F414F4AEED
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
