apiVersion: v1
kind: Secret
metadata:
    name: speakr-secrets
    namespace: default
stringData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:Vm9i5sowB9OprQth6HJ3HQYqe0S6E/iqh6OA9zcO,iv:WzVbnNTw3nL1KNOJhpwaW6/UjXOGpXN5YBhVyM7nG00=,tag:GkGq5UJ9w0cQ+HFElirvAw==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:b5OQyiBtsLuj9t3aRmRTd6+ul+ldgT2X5elOd9wX,iv:U2t5iYCIf7ufQXpWLJiUtOvxDfyqZIc+C5tHE7QczCk=,tag:wHZNMT1F6C1sh1/3iTOjbw==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:5Nh/ttqDCqaBJ0ANerC6Q3WbH5KWBU6wMAU7JTGSabJQZsW+UdamCTKppNRb5W4tEWnuCDqQHNE9iFddnoQfLeINI0vjBK2gbA==,iv:2oC16VlFOcjOrCmpp/08IMhnvKC1yvxHpMk3Rg19a5M=,tag:8Llp3LjWwzB1UfBHZ3lvTg==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:I1vXQ583H9wfBwziySLIVau3R9EHrUuoZ3sdCBG9XGbdNLwaKZtZjslCpQuj9DHDGLbkacvbDGnDvPOPMQry0xtCTnJGlXpi0kQqSMCtOvVJj4SwYlJ3cN0gMEzY1bOkjSd6tvhnq9uIsoE93O4qGYGmqISTrltZQtqhz1bO2MAdm5mOwghjA7cvrIw6M7RKxGuiCsHo0HPX4gWIpFt1eY1sSSA=,iv:6RSvWhVEGegjc7o9M+61RElxSbCOPhRi08MGjNKmanI=,tag:RubzlMYhtlcbCL5O1IjoQw==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T10:34:16Z"
    mac: ENC[AES256_GCM,data:fizdrcmDSCs/G0x4fH3FykhcwG270y4lCEFeIMlzZ7w9HlRiE7WI0H5Qp1qVEeT2nu6x1NplOLksVuQcrZHUGYwAJA/hqoxzvI3eqSFciSwApBXE1F7nMJLpOCX+WluW361IKHu/45TkPfb+TZZ4QY13HGS0+y0LExYA/8oEFXg=,iv:LYLzgLja5roi4WdDvQ0h2ZjwACXuvVueL7zvYbAWLs8=,tag:QMDGG7OC6grX7MsOOxgrmw==,type:str]
    pgp:
        - created_at: "2026-07-28T10:34:16Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA71EESEn7N2iAQv/c4RRksFyoYHXDSUw0lzfF+F1Bbm14fUS7bxtkyePAr9G
            kNRJMG2mgyGnSAQPRRvNlNLR2U5cCU00VNxd5pB8UqvE/1R4NaGCeRkrdxHZsNnf
            j+9PJK6fokqB64oAdy56xUn2YePGdBXtqYUxBnOBvpqwCa+pmjbz58kfSyedJuo6
            R3fmtAie9LYmh7udIMIl5i3sNb5td/eHo31KG7cEMg4UGo8dh29o2JO8SOPr6Nh5
            AtKNf6T/3IRky7jYipeSEoQTqff/1vPqLvTGYDJujEWi0Yby0BnwyQc3c/HjxklO
            kXVxLAGWbHxAjJmH5XL+C/BOfy3ElpkF82a1n4zZYHjyHjTXXYWNUn2BVBM8cx8N
            Z6vHhIp/x9/IUrOPjvO034z4Wc4NGFEUtnkv7eXwSLSBT7ENrFV5jNeJyQ57zazK
            PAvYjKuv0IyC99vbLy2G31ghfnspHi7fFoxyXuZT4CXZu1A1L8+EXlF91J3AMXdA
            /VRykhwetwfuaN8WSD7G0l4BAcFUqjenKSV+XBxeCzvWpFNKes+quh6bW+S2CWpw
            dl6tmN5y+YWbZxm6agr4yJYGJnikX8O2DYugrpWA0tvmop/+xLf96S5UImM3BNjD
            55J3cYnFsuvmrZef1izt
            =x2eD
            -----END PGP MESSAGE-----
          fp: 2D47B9C25AAD87860CC1778F7022B8F414F4AEED
    version: 3.13.3
