apiVersion: v1
kind: Secret
metadata:
    name: hermes-h-secret
    namespace: default
type: Opaque
stringData:
    HERMES_DASHBOARD_BASIC_AUTH_USERNAME: ENC[AES256_GCM,data:gKmtkP0S,iv:3BA8o5PhmTk9k4s2c9UUBj6aWVzN+X3ceTUNFoaTY5g=,tag:wymEQnWGh3JDNxMgexDGqQ==,type:str]
    HERMES_DASHBOARD_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:swl1nsIxKj2+4+xuMTb5sxg5aAAPt87ysBlSp5l4,iv:11iTMSY0iDeG35q6ypLgKtn3527FUlmr2VYJRpKg9II=,tag:6Ui6XxVkvLhIcpdAEnkgsw==,type:str]
    HERMES_DASHBOARD_BASIC_AUTH_SECRET: ENC[AES256_GCM,data:7qIQLEX1Urjhj6hVtZ2fFaLKatSqqWm4EKUdlXK5kzzeeWI3Dp6DUg96his4GYrineZwy92Jqw2SKmOkZdIvjQ==,iv:/17WZpSgjpAvTNbi8fUTlMjwNz1OiTt7fZtjoRNl8zw=,tag:fMDVRC+YV8Ug+Mi0QxdJ+w==,type:str]
    WHATSAPP_ALLOWED_USERS: ENC[AES256_GCM,data:PmyzWhpy7R6vO4eh,iv:9Lzm9Ay3YMxV0n7lKzRKTHwPLJbXwvXNs9Yham86aIA=,tag:JsYwswq/YgM7ALUiaI3ohQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-03T15:00:14Z"
    mac: ENC[AES256_GCM,data:kP/yEIRDcmrG7eOf2XEUcky7dsghpJGlrv7xSaxS93q+Vqge66dnnmIL9bG4ghy1FAkUY++vlCFpi6XQkdB/q/JiM+iFrrILB1Sku+uoy2k6dn646uU3hcCacMaMz94f5HzgqyXG66zNrrDK2hbYGY3VN1juypN8AT1dfa/MEbo=,iv:I2ZWdUr4KIjt/N8T4hDjDH5Mb6zY++bBW/UNbqmzBm0=,tag:ycfQ0Deg7EmqmT4hSaLExA==,type:str]
    pgp:
        - created_at: "2026-07-03T15:00:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA71EESEn7N2iAQv/cgdEziiBqw4zEK37W7v6QQBzfiiDTo4/3YJDHbUDM8X6
            rL8xuLKuXcLJ/Z2CwyQE7nBZcbjz3ksr9lMTyboQr7ftv3vDxL5BeWJvmDk82nux
            e5Jvbroxs7XpQpdlMhXGhP/t2oqSDD8CfRdofDpOUYNUqKwBhsFfKCdLTcjYDfVi
            jhevJ5+QozIg0Lb97hzdb8k1KONf6LVTlFFNp9Bc7zqN0FRAwLbVlqMuVjgSYVkp
            BwP76a/85QeLfvPwe24YJYGa3J+HiFWjhuLrdEl9G0fQM+EqRNBc02e2bREYfHEt
            Wiz+cGPxVZ/4Rx3fVl/JB1YtWwrUJ/BQcBMBssthamsFAHhpyRh84zAH+DenHaFD
            g7Hnp0ziL9mvNlJNhzwXqy6bcXJLukzCmB0OAH+KG7j7Qk8YpZML80HvHCVWdn9r
            17rKd//niOzyOBzZYeXTv48YZDDRlTwU973XamdVjk3jdDgsDWSTqK8vcZ0XpVyZ
            oJzJBmpHyRkKA5m+2MXa0l4BwEr7ZveKcTeXL8ndXksL7Bl9HN+1gGc8ac72m03S
            QZ436YHx6PqNdSUeNw5+IL1E5ySmST7UArAkSLmCuJ26lZP1ck9crNpMvXPj4Omq
            O1oP+yhb0NfIyNLQb2uZ
            =c/tu
            -----END PGP MESSAGE-----
          fp: 2D47B9C25AAD87860CC1778F7022B8F414F4AEED
    version: 3.13.1
