apiVersion: v1
kind: Secret
metadata:
    name: hermes-h-secret
    namespace: default
type: Opaque
stringData:
    WHATSAPP_ALLOWED_USERS: ENC[AES256_GCM,data:htubDXnzrvJbH3YZ8Q==,iv:T3KhbOHe8WfseLeHdyt27CaBGaWH8gjgv/S/oqGJBBM=,tag:UTRLj1zRdpL0YHj2cYhnyg==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-11T13:21:40Z"
    mac: ENC[AES256_GCM,data:KP8dcdlrP4w3t7vcQNbqVvXS9HLFzwCpAI1ZpvQtywMW10+4CFIVKsPUGY44sy95nWhvbf9WfVi48lDX/GU+E2g7iv+rmh0IbjMm5VrI5EkCJlhixJ/xK/59oXtwTQc+VZUjUecqJyWvj/CguOerBm5S+WuNjSJz+JDxjq+KXYs=,iv:fHNVLSoNcVBzpgVf0UptJVSliZP6D26pY3Ch01M11P8=,tag:PDAdHO20CHY4UTSLwP7WDQ==,type:str]
    pgp:
        - created_at: "2026-05-11T13:21:40Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA71EESEn7N2iAQv9ExpHp7g6QSUj9m7hQkvKBtRzwh6PwnD6DuCXPxlMFlXz
            quLhR9C2cIo4vGVR1U2h2lTQONOGCcDgeCUvvztVaRofdz6h9rl5NAGuJeCbeOCg
            c87mdzbdsOKKy+KzHD3qyc7YvClP6BXmTL+1mbkUKtHSabmeVRO4tq/SrhhQaW6Z
            IsenDEKXZB5a3LZWhvu7C8xW+pPyBHZOtN9r9L35SVHoj/oG9w1xDjSUhY25zN6L
            Iewb+WK0qVcTf1RcwypL4XNQXKytWyvu0scV04jCab6aujvm1wpBhXx/2ogRiAWe
            bcMf6m5HzVUgEmZCEfwHA3noA5MUMl+l281cx+nHamTG8gyizSoFv4+HF0MGMkVl
            XBKN6wfi5qjIPGYgu9R4wq7QnlZiD5pS8glxltkDqkPzThr7Md8MIOURlApobNTl
            AFP2xaPBX/VcHJKSIbV+pT/8C6IBWVS/nsx/6c959YGtFns5XHsokGU/k8g1iFNm
            j8vqHUYz1/kh6PgB9+1d0lwB9Z20EU9ND/AiaRMvzCXyYrmnZiCXGjtGZp5174bv
            cD45GqyAa42H7slQTCNlhIRooVC0SSvcvOiSODftn1ynMO4Hg9i46dXn9C2V00j8
            qeEotGB6U4Jc2/5HsA==
            =uIn+
            -----END PGP MESSAGE-----
          fp: 2D47B9C25AAD87860CC1778F7022B8F414F4AEED
    version: 3.13.0
