apiVersion: v1
kind: Secret
metadata:
    name: hermes-h-secret
    namespace: default
type: Opaque
stringData:
    WHATSAPP_ALLOWED_USERS: ENC[AES256_GCM,data:lcqibKTJGXdjn0de,iv:Fo8q02oQyfO/HALbgXGul9dnbSGddHag5e+oQG/MLpQ=,tag:avQGYw4C7G0x4pPQ3XxDQg==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-26T21:51:09Z"
    mac: ENC[AES256_GCM,data:eDfXtQp7bOcFTl+CnbMtqx/gEq6PlE3ifTL7CVtXHGeSaHjmXj/4aZsTWrmoEMstujKmuw5Ut7BKzFGeaFkp3gavRt+I9uhW6KiWRcl8oYj1RDVuJ1rXEa8TsDt6ya12TI5zez0LgxYJ5PnDKcG2YE/1LZjALjM3WnZJAMWhK9o=,iv:ClC75rG79ElP8cLWO5lH0oi6V1ibxleEowwaQkWk21k=,tag:u3plYEMddI0i8vej/zPlPw==,type:str]
    pgp:
        - created_at: "2026-05-26T21:51:09Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA71EESEn7N2iAQv/bv7y6n/uheekE/+isVS+DXn3c84Kk2hhlC1PQTBJ+Kxs
            ikwktE4jeYQIbLRy7P6S/U/G42xdvH/AGogAW7nnnRA6su6tniKr/0CHDmZpwwiV
            lWUBTKt2wL/rAVvFjeMoGGdr9zrgsByosg+lKf+va0DB5iLl3VxvnLL7FHe5y5SQ
            wv1YmT5DvI16ir6U1NYCQOenlVNaiiyl7qukPOvqu9dUbyIrq0yRi5PUUGc3/Soj
            jYKdUSWzHarRp3PQu92KIbflbDxInR1+YuBqiIo2AK4rLMoQrmhRXXIex3saOjhF
            Mu+Q8OtIJCEhg3lHUON7LN3R0bEPc3pGZRRVypsFp8xEDOzG5M12JIMsQPWdXMzN
            bjruW82eFRDotptwbLAayoO6ANcJvVjgHRmaxh1Jr6k+FQ1l3ZHsjNVqawGrfnAK
            GWMuN9vwXa+lKRthH//PVfs/Ivnz9PmjXn8Hx763V+7++hwuVQ2rj0YQLrhgitje
            th/Dn2oMUxMocPAPMyZs0l4B1hYkPWagRpJSaSghSOjSzJ2OMt3VcTH/qKSWFJXO
            Hr3MaGxInS3nYQUlHUgYYyebnlq7MMFuGNIVesZI1vbu6EVCD0umvABPEkTrb70O
            XFqiTx5UMfz2QAK+MckN
            =Wtan
            -----END PGP MESSAGE-----
          fp: 2D47B9C25AAD87860CC1778F7022B8F414F4AEED
    version: 3.13.1
