apiVersion: v1
kind: Secret
metadata:
    name: godot-access-v1
    namespace: game-development
    labels:
        app.kubernetes.io/name: godot
        app.kubernetes.io/component: access
immutable: true
type: Opaque
stringData:
    id_ed25519: ENC[AES256_GCM,data:CsTCXE3A/sk0j6ijeite6b/pB0LkZKFcg5svpZd/ubU9ubwE38y2KSQJiZNG4s+kt6qYrI5aihUERTSdMjDqkGMFwAzMYKFsDyl90kJfjNaa/IQRYTCmRkKdhcr4wk24LOI/FbdWfiFEl0gJdOEwPe4NlLaKFTSIm1uSpz3ogOYqLC4/dnKJNeOpgtyhgL4/LNYT7NZa+d0RSek/bPJzXTEohm46/KjQnKvaAeCNg2O5Nnicqh8iFALdy1yHOGo1jiaQhnPZOzNyR0dUPorbTMkDugpc5bpZiVRkSXMyiLbYS3zKaGh1XGGKgVfSGY/CoGV0o2Bv2ldgwCqQ0DO/OaWqtA8hFCZ2C3Kp2pDNm6GFoQlOk7XRhPsJAOHnovDbWwULXYFgPlMLZujCuvILHXVDEX3Zz1FlARwgW2vXtujJe+IPdXLb4JGrHjPDl1Fc5MxTpkAVE8GPRxbA3wCKFA4Vani+sF5iWU3ZqSqWXK8ooYbxN9phP7mAbQcbzrEWmHnuHZJZodCRDpCEndfYhvc27yQvoYL3UItEzPOnFQ6BK+AqiF6m/Azjqs0BUcgE,iv:URlQG1k1G6BbU8P7Jp9GSKs/QopMzCXTnXuAFo4hAxg=,tag:VBntIpZfiDxqqp72GYtfYw==,type:str]
    id_ed25519.pub: ENC[AES256_GCM,data:2caZXqriMEbze8yerdkC/mee9W68oEJ2wAXD3lG7v4Whc3nIxN0ZhnquXwz4+fookqvmM4eG8VEMFbPz1aHsnjIZqVgnf6CcWLwPHz7RJGyGBvLn/01L8Fhnq9TFUpy6I2uhZxzD+T0Wos9FkonTn1NZEvKA,iv:tphS9PPeHakoVDCQPzCOVGLlhCEtFAiQkAg90cyMNq4=,tag:nqzIfwOgRYb6GJVLdArCug==,type:str]
    ssh_host_ed25519_key: ENC[AES256_GCM,data:NdYLeM5tG/7a0EJHVdvj8uLWwmkwJN+sPP+mN8+oj7+C0iDWGmK1EIg8nQJOBQo6/P7T4wmwDjIV8XdINErRttMoJZ6mtypTDXYZ1Z6TBlUTyCCW66TSXCoZPvils+XkMnBgfs3CS4uj2mNRw8lPoUfvZEMheoJOPZkP6YjpSEYJnInUT5RSDxxxfilB4GhHXI7Hm8wf39eCm1GXLTOvOf9YNCsRM1QL4rpjK8oriufKHFLU8L0btl00HFYP7xiHenm2DNw8SpQU7HHsesYeKVBbNZ1r8t1nGyvzqKDGFI3RtOSGSzzIelMkLp8MKFlxAb38TEhCgpuWcDWngTPx+nimAn/VuFJTREfDR7O11bdcnZgaiSOITqBDkXJv7eG9AxIl7WudnP2WlHj5qejG10Y7mpleIkj4zJ/9tpYSG4kR8opbaKdTu8zoAsco+FPDvdhqSRoyVNYNXDBvtNpysR4hRIU7nvtSkNl5BT/457QWzX8czSy+WojK1u2dq/VH28lWDSUBzxzHh7xCsvSbbD0hvbj3p6cikCeDEzcHRwrkQObF1QKGRv3UoB6LN1BN,iv:WQL++tZAnvEKeqbnria/pFffQaNk/n200eM+Vom9lMU=,tag:CktW0pcTm9XVJP0RCkEyug==,type:str]
    ssh_host_ed25519_public_key: ENC[AES256_GCM,data:pW9OHcZZeaVYJgCwmfRmhefbCi9RkgYqcvCKg5T1qFQTL4kw7r8+X4WY+sWJVzz1HIUTcIAy6w0T3xT282ZG65jJ7hfQYoP5+aiXu4L/q6H9EzrTaIQJDCbpJrswU01xbhVI142U1RwnwlTzC6bTjkt9or9U,iv:MC3vicgwRwNeehRBOtTJbbs9asv9Doz20d/JRHFabyI=,tag:tLB943OPIG/mcRjgTnKJ1g==,type:str]
    ssh_host_ed25519_known_hosts: ENC[AES256_GCM,data:wtiHMO5hKpsWd4WNY6EB0CrcbI18VG5kLRzlGBI+gkdMfRIyXDznDMTPd7a++Ehw6gNxSZaUAjOpmEdFJIX4Z1Sr4oQk5ALJGIQqaoWOHCFSVUArmfWN+0AU4oC494Oi2z5KLsMicGuotBztvnSCKgQyZ+752ovC7jZAo84KvogWHC9/9/DFr/sHtbjmJcw2h2W3zT55jTAwvoXqDQvBAlHz,iv:GACI02b3pf7bl81Zr+Iu4J/j6cQPWCPRIxGKJgBSnqE=,tag:9INSVJyJHyByLcawmAEbNw==,type:str]
    browserless_token: ENC[AES256_GCM,data:LWLrTSZwQAcz5JVzN9jA9DXY/qa4cQJAzUgAH8Gf3BiUNhgd0MxVExGcAjWbPf7EJ3e/1O4cb2ruh+q6CKgkJ00=,iv:QMiGM+bY8+fErurDrqy9u6uJY7JbmIJ6s+VexSZ+B4o=,tag:0Vg/YkydynRnS1d+BnVpKA==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-20T19:55:02Z"
    mac: ENC[AES256_GCM,data:0aHjLgSlUmSahedmXX9Y321hjVz/rJzcKFbDaYQ86+QoairjgazsWY30twVBabnJ2gBBfhsQ9KzC+wmNZhlIF0Q6l6GPLEpN6ZcxIuSkqLjJgjgFGb2YaiGNPA8TG8Nrk6Wecs69bzwR7Lw0C/8Jb7pK7G6FYwV8JodfCAh1txk=,iv:g/ksykOwiW2wQGS9ALj/QMVgAoLCjqI4m+PdAztnrps=,tag:lhXJEXh6wi+zjLBSLOkc1A==,type:str]
    pgp:
        - created_at: "2026-09-20T19:55:02Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA71EESEn7N2iAQwAkIdMhbz/7Yvz88AurPXlbw3Depx/WzN1gI0nxl+h782+
            Xhp34wRlj5u6Gk47lXlpsSrVM47uH/qFJaOB4XP9/6uLsH9tTnU1LDWffCMBtqnl
            yxY6Tlq7iaf7nEvre05Msw+nYNY07fCPldEV8p5Qp55ZH2+VhdoDji9By1PlQL5f
            tO7K6hVCJeEx7dYv7CskjJn/N2mFuONbi/aRiQnQUrqBkv1xbjocPhEtYJxithVY
            veMr5coZLEJff6E2cYk0lT7axKrwycJF/omMauIzgFV+Esl2gjU25C5aK8DLaaCN
            AdbKkR9kcHOqK2mDMM8WvbsUH7+jYVkuVYm6PXrr/Dr+l9gZ83oB5Ofbb37SMpJF
            NHNtS+1J+lcLiVYvbukfL583ffGwdi7QMXu+i3bWTtdiVlHzIA4Xq5MRCMh8gOmr
            UNn/70x+qujKimIL+GjNKqi6CzleGwMCeEzcnrIZPf5Rp2JIFmGiHPj5gWJh/hQU
            wAJg3EuwkXpfLWpEzwfg0lwB7fjLIhT2G0L07dyi0SmlQ112avDGsyx4scQ0MKBp
            w880O97Yo+e9wZmr4f12HGQFRx0A+qzaheQ8TGh2w1lKiOAWM7bx3xrIA+UlcG5g
            ccRbVN95z4SUZCGeSw==
            =xYFm
            -----END PGP MESSAGE-----
          fp: 2D47B9C25AAD87860CC1778F7022B8F414F4AEED
    version: 3.13.3
