apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orychamber-data
  namespace: default
  labels:
    app.kubernetes.io/name: orychamber
    app.kubernetes.io/component: data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orychamber-homebrew
  namespace: default
  labels:
    app.kubernetes.io/name: orychamber
    app.kubernetes.io/component: homebrew
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
