apiVersion: v1
kind: Secret
metadata:
    name: orychamber-openchamber-secrets
    namespace: default
stringData:
    OPENCHAMBER_UI_PASSWORD: ENC[AES256_GCM,data:VUv5sUTe08B3K3xdTJ2tJTm3vLDperS/JwBY+sClYTBZ+rRh,iv:vg+lcgnPOwJAjeKfEEIE2vrvXjrZgffl47p86BAmQDM=,tag:75fvraLLc3UswqJ11gN11w==,type:str]
    OPENCODE_JWT_SECRET: ENC[AES256_GCM,data:fFNPrSiHuC4of5PXEen9nR2TU3eXeIgfkFQ3a51z3ww76kI8arGdN0gRyJ2daSu9vG6RC5LyyG0327/TL6JS3A==,iv:IS3eSzZJD55wAH5L0mVGB2CxtVy0kCFVBgucUzGWGPQ=,tag:Rm03nF26MvdEAupcORaqGQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T10:03:26Z"
    mac: ENC[AES256_GCM,data:yglHC+YvgY2ZGRPJCc3e9mYNsN6S3v0QX4hDkSub4kViyxWkQpyVBSqTXvyYUc6VFOqf1xMskg8HMP0fgUx4su5ndDP6W6OxjaLzmE7Rj3OPdXTKTYxPIaGloH4g8SN0UP6AD4xEz/U11mFmIY3gbDC8e8rWljpc4fsx2w27Fdc=,iv:5FZKBQ4O+iHRqlvQPHsWEdOyPmEMaE1jFSkp6Nmcuqw=,tag:OhmmRSX6T3X3qHuLK5RKDw==,type:str]
    pgp:
        - created_at: "2026-09-19T10:03:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA71EESEn7N2iAQv/XlFfo9H50Y2vj3wjxpCgRTI+uDkkIHmSzcr/Ii3M8khM
            tAnRhQ/jf2j4FNjqSzLKXaghZJ25I1ePq2b/41ANSUtp4IrSqdQtYE95Pkr68A/k
            /JkNTLOIruWrbvfRhUP5wwykOy5kQ1fQE34xqduAAxVrXbAF3Rvd5s7JiTeyrUBx
            1h7Thyk656L2/rxTzI+Q4kI910bM8XHiYww7XrhSsguVDW1yFEhBqW0riQTztdna
            XD8YRLA+pQmslAisXfxdc5h6sRMzV4uqsS+xSf7KvroIb3ycB1fa/XHij0OS7BSk
            /Gd11BlVzzoQ7i7w20m0k46phVPsZBjfXyMjtrz5OuVYAWwKfdxZcjHdGJQUmgoa
            f7bZulU3BPdDrNRB+AC2P2Yp8mTnZCfLDw0qCbzErnw6MbgMk9bxcai9vgt1WPH2
            28jLeVl4EusIkphz3A9ot11dyb/T9v3MM2vM88kspFcfuFRLs9k9eliB0VDUwjYE
            QJdDx9A0rQELCzEZO6540l4BbVEtDEEXCQ+Z/Gy90Ds/ROJl25m3/4mx9ZcvkeMz
            AsHEVtQ95TLyWa2njlvpTxlwMZtZNIxqF/iFaXrdHV+bSGyaA1mF7w/TJsZOQPDq
            ymu38574d9e9UkegDFet
            =Pih8
            -----END PGP MESSAGE-----
          fp: 2D47B9C25AAD87860CC1778F7022B8F414F4AEED
    version: 3.13.3
