apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hermes-a-data
  namespace: default
  labels:
    app.kubernetes.io/name: hermes-a
    app.kubernetes.io/part-of: hermes
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 4Gi
