apiVersion: v1
kind: Secret
metadata:
    name: hermes-a-secret
    namespace: default
type: Opaque
stringData:
    WHATSAPP_ALLOWED_USERS: ENC[AES256_GCM,data:c1YEuW6oMwZoNRKrMQ==,iv:fOrbUccKI66B3qaCTgx5d/KC+/MOdu+5ow7Hoq0K8YI=,tag:GwloDO00UJeyuUwSRoHYZA==,type:str]
sops:
    lastmodified: "2026-05-10T19:51:34Z"
    mac: ENC[AES256_GCM,data:h9OEyABgsKpZP26eKDviqBaIe5mf/gk89zDN4tNYpRkaxCyo9y8VIUZxY16N2JVefaWjCnT2ovprWBxOniwJPOm282GgZR3BLy6zz9VcRVRNLgeLGEQLLogUU76VM/EgKTTKD9gPPHyO0WnwwjTF0FyfJG7gixhA3R2i3xSmD/Q=,iv:VJUv/xWcfUTQjMZJxcMlDrbSxh8Il8Z5FK+8uBJAaDA=,tag:ZFwg5JoW1lCqPMz+J/qOsw==,type:str]
    pgp:
        - created_at: "2026-05-10T19:51:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA71EESEn7N2iAQv6AiDDB9IYaXzhaPAiQZC7GI9q0IzMzoq3oCJL/iUGcEJO
            wiUuVWYjN6P+j5LSJcZVIdDKO+TvkOLJJIrKzPC/3T12/rU29APPjvxjABjwHpsd
            JgkynGyWVad4Je75+W0r98Lcdr+szFAj8qL+d0VkM39E35guLtxNFLJnuvl122uW
            QvmY6Ufx3PcYDfdR9WEVsYYGxYD/CnG116ba4w7tyXVT4Yo2szIMvHmkK5AohqjC
            u2n05CkS+D6Vt0m49kGBhJNoTiNAMhA90/ns0Rfxlnt7hxGS5P+FxyYpQS6XSXMF
            28qFlyI0EhGSJiOtHsP+TCahuF8+GUm+Ic4Pu7X9Nko1epzvLYAnKH0gqdWwuSY0
            URwc/EByyu2rAAh87QqUa9dj1zviIU3JoIsqntdBHZIPYatQlfRATHMP9qP65Aye
            +GT0f6Eae4qH7rOqH01oLapiU2cbVrzRIlJYq6JprGPuCPM9ZVGOf6JTlnVFshxl
            6R7GdqoVV+7FWI0cRJlW0l4BmoTBShUHk2uJpJNKp+RQeqb2PBQZr8D7hkGsjY/n
            UmCjkiBbK0kAFgLM6It0xPfHhuXVzeuxk2d8XMVnBs3Dg7Vb3L4zXWy5NNA9oJ4r
            iyrzW40dY+4qhtckU3GO
            =v5OE
            -----END PGP MESSAGE-----
          fp: 2D47B9C25AAD87860CC1778F7022B8F414F4AEED
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
