# Adapted from https://squidfunk.github.io/mkdocs-material/publishing-your-site/
name: Deploy MkDocs to Github Pages
on:
  push:
    branches:
      - master
      - main
    # Only run when docs specific files have been changed
    paths:
      - ".github/workflows/mkdocs.yaml"
      - "docs/**"

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - uses: abatilo/actions-poetry@v4.0.0
        with:
          poetry-version: '2.3.4'
      - run: poetry install --no-interaction
        working-directory: docs
      - run: poetry run mkdocs gh-deploy --force --strict
        working-directory: docs
