# Adapted from https://squidfunk.github.io/mkdocs-material/publishing-your-site/
name: Deploy MkDocs to Github Pages
on:
  push:
    branches:
      - master
      - main
    # Only run when docs specific files have been changed
    paths:
      - ".github/workflows/mkdocs.yaml"
      - "docs/**"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - uses: abatilo/actions-poetry@v4.0.0
        with:
          poetry-version: '2.3.4'
      - run: poetry install --no-interaction
        working-directory: docs
      - run: poetry run mkdocs build --strict
        working-directory: docs
      - uses: actions/configure-pages@v6
      - uses: actions/upload-pages-artifact@v5
        with:
          path: site
      - id: deployment
        uses: actions/deploy-pages@v4
